### ISSUE TITLE
Uh-

### ISSUE THREAD

**Issue by DaChickenKing** [TehProdigyHackerz/HackingProdigy#2]
This is violating the license of ProdigyMathGameHacking. You seriously just copied the code and claimed it as yours-

**Comment by coolbot123** [comment]
Yes ik

**Comment by DaChickenKing** [comment]
"3.1. Distribution of Source Form

All distribution of Covered Software in Source Code Form, including any
Modifications that You create or to which You contribute, must be under
the terms of this License. You must inform recipients that the Source
Code Form of the Covered Software is governed by the terms of this
License, and how they can obtain a copy of this License. You may not
attempt to alter or restrict the recipients' rights in the Source Code
Form."

This is currently in violation of contract law. This repository violates the actual _law_.

**Comment by DaChickenKing** [comment]
"3.4. Notices

You may not remove or alter the substance of any license notices
(including copyright notices, patent notices, disclaimers of warranty,
or limitations of liability) contained within the Source Code Form of
the Covered Software, except that You may alter any license notices to
the extent required to remedy known factual inaccuracies."

You guys removed the LICENSE file, The CODE OF CONDUCT file, and the README file.

**Comment by coolbot123** [comment]
I'm wor8on it hang on (I'm yeetus)

**Comment by DaChickenKing** [comment]
kk

**Comment by Diveodile** [comment]
> This is violating the license of ProdigyMathGameHacking. You seriously just copied the code and claimed it as yours-

I am sorry!
